name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
        sudo apt-get install ffmpeg
        sudo pip install pyaudio
        pip install --user pytest pipwin
        pip install --user --upgrade setuptools
        pip install --user -r requirements.txt
        pip install --user -r requirements_dev.txt
        pip install -e .
    - name: Test with pytest
      run: |
        pytest